version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - npm install

  pre_build:
    commands:
      - echo "pre_build phase"

  build:
    commands:
      - npm run build-vue

  post_build:
    commands:
      - chmod 755 ./scripts/*.sh
      - ./scripts/create-build-summary.sh

artifacts:
  files:
  - '.ebextensions/**/*'
  - '.platform/**/*'
  - 'Procfile'
  - 'application.py'
  - 'config/**/*'
  - 'consoler.py'
  - 'dist/**/*'
  - 'requirements.txt'
  - 'ripley/**/*'
  - 'scripts/**/*'
